# Generated by Django 6.1.1 on 2026-10-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebalanceevent',
            name='execution_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DRY_RUN', 'Dry run'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
