# Generated by Django 6.1.1 on 2026-10-03 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.stock'),
        ),
        migrations.AddField(
            model_name='trade',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='portfolio.portfolio'),
        ),
        migrations.AddField(
            model_name='trade',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.stock'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['portfolio', 'date'], name='performance_portfol_321b6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performancemetric',
            unique_together={('portfolio', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('portfolio', 'stock')},
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['portfolio', 'status'], name='trades_portfol_5c541d_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['status', 'created_at'], name='trades_status_edb12f_idx'),
        ),
    ]
